const Images = {
  BackGround: {
    Bg1: require('../assests/images/bg1.png'),
    storybg1: require('../assests/images/story1.png'),
    storybg2: require('../assests/images/story2.png'),
    storybg3: require('../assests/images/story3.png'),
    story4: require('../assests/images/story4.png'),
    story5: require('../assests/images/story5.png'),
    blackbg: require('../assests/images/blackbg.png'),
    black: require('../assests/images/black.png'),
    greenbg: require('../assests/images/greenbg1.png'),
    wolfwoman1: require('../assests/images/WolfWoman.png'),
    chuchuhuas: require('../assests/images/chuchuhuas.png'),
    BlueLotus: require('../assests/images/bluelotus.png'),
    BlueL: require('../assests/images/BlueL.png'),
    croped: require('../assests/images/Wolfcropped.png'),
    lageChuchu: require('../assests/images/largeChu.png'),
    larggeMushrom: require('../assests/images/largemushroom.png'),
    largerose: require('../assests/images/largerose.png'),
  },
  Logos: {
    logo1: require('../assests/images/logo.png'),
    hands: require('../assests/images/hands.png'),
    layer: require('../assests/images/Layer.png'),
    layer2: require('../assests/images/Layer2.png'),
    lotus: require('../assests/images/lotus.png'),
    greylog: require('../assests/images/greylogo.png'),
    greenlogo: require('../assests/images/greenlogo.png'),
  },
  Icons: {
    upload: require('../assests/images/upload.png'),
    envelop: require('../assests/images/envelop.png'),
    light: require('../assests/images/light.png'),
    circle: require('../assests/images/circle.png'),
    triangle: require('../assests/images/triangle.png'),
    bluee: require('../assests/images/bluee.png'),
    heart1: require('../assests/images/heart1.png'),
    small: require('../assests/images/small.png'),
    leaf: require('../assests/images/leaf.png'),
    gheart: require('../assests/images/gheart.png'),
    gpluse: require('../assests/images/gplus.png'),
    spiral: require('../assests/images/spiral.png'),
    star: require('../assests/images/star.png'),
    arrow: require('../assests/images/arrow.png'),
  },
  Imgs: {
    pic1: require('../assests/images/pic1.png'),
    bird: require('../assests/images/bird.png'),
    bear: require('../assests/images/Bear.png'),
    women: require('../assests/images/women.png'),
    jaguar: require('../assests/images/jaguar.png'),
    Rainbow: require('../assests/images/Rainbow.png'),
    lotus1: require('../assests/images/lotus1.png'),
    rose: require('../assests/images/rose.png'),
    rose1: require('../assests/images/rose1.png'),
    rose2: require('../assests/images/rose2.png'),
    rose3: require('../assests/images/rose3.png'),
    rose4: require('../assests/images/rose5.png'),
    mushrooms: require('../assests/images/mushrooms.png'),
    cuhuchuhuas1: require('../assests/images/chuchuhuas1.png'),
    chuchuhuasa: require('../assests/images/chuchhuas1.png'),
    cuhuchuhuasb: require('../assests/images/chuchuhuas2.png'),
    chuchuhuasc: require('../assests/images/chuchuhuas3.png'),
    lotusa: require('../assests/images/lotus1.png'),
    lotusb: require('../assests/images/lotusb.png'),
    lotusc: require('../assests/images/lotusc.png'),
    mushroomsa: require('../assests/images/mushroom1.png'),
    mushroomsb: require('../assests/images/mushroom2.png'),
    mushroomsc: require('../assests/images/mushrooms.png'),
    mushroomsd: require('../assests/images/mushrrom3.png'),
  },
};

export default Images;
